### ISSUE TITLE
NA group appears in group drawing

### ISSUE THREAD

**Issue by moyangpei** [immunomind/immunarch#7] opened 2019-07-01 13:43 UTC
Hi
I checked the group information, there is no data missing, I can't solve this problem, can you help me?
my code
vis(imm_tail, .by="Type3", .meta=BJclinical) 
![Rplot](https://user-images.githubusercontent.com/49758857/60441202-13c90e80-9c49-11e9-9d86-b40d690d915a.png)

**Comment by moyangpei** [comment] 2019-07-01 13:47
In addition, many detailed parameters of this package are not listed, and the drawings can not be modified. Can you provide a more detailed manual? Thank you very much.

**Comment by vadimnazarov** [comment] 2019-07-02 10:53
Hi, thank you for noticing that! Can you please send me your metadata file? Email: vdm.nazarov at gmail com

Drawing can be modified by using fixVis, see here: https://immunarch.com/articles/7_fixvis.html

Can you please provide a list where you want to modify drawing, but you can't?

The package is not released, it's in under active development, so many features and documentation parts can be missed. It would be a great help for you is you provide us a list of issues and missing documentation that you want to improve.

**Comment by moyangpei** [comment] 2019-07-09 02:36
Hi I have sent the  metadata file to you a few days ago and look forward to your reply.Thank you very much.

**Comment by moyangpei** [comment] 2019-07-09 02:37
Hi, I have sent the metadata file to you a few days ago and look forward to your reply.Thank you very much.

**Comment by vadimnazarov** [comment] 2019-07-09 07:32
Working on it! The issue you described is much harder than we expected, so it takes more time than usual to fix it.

**Comment by veronicanoyaro** [comment] 2019-08-23 16:48
Hi i am having a similar problem
when using this code
>p6 = vis(imm_topTCRd, .by= "ELISA", .meta= TCRd$meta)
>p6

#ELISA is one of the columns in my metadata.txt file contains NEG/POS/
I am not being able to actually group the samples. i have 30 aprox samples and they are all plotted in each top clonal proportion x value , lets say 30 values in 10, 30 values in 11-100 etc

the plot i get would be something like this
/home/veronicanoyaro/Documents/PASTEUR/TCRCLONOTYPES/ANALYSIS/IMMUNARCH/TCRD/Rplot01.png

I have also tryed to pass it as a vector like this

by_vec_ELISA = TCRd$meta$ELISA
>p6 = vis(imm_topTCRd, .by= by_vector_ELISA, .meta= TNA)
and i get the following message

Warning messages:
1: Unknown or uninitialised column: 'p'. 
2: Computation failed in `stat_compare_means()`:
argument "x" is missing, with no default

**Comment by vadimnazarov** [comment] 2019-11-04 20:34
Hi everyone,

this issue appears much more complicated that we first anticipated it and we can't reproduce it.

@moyangpei can you please send me the code that you used to generate such plots?

@veronicanoyaro can you please send us both the code and the metadata that you used to generate such plots?

Thank you! Looking forward to your responses.

**Comment by vadimnazarov** [comment] 2019-12-04 14:07
Thank you for sending us the code and the data! Can you please update the package to the latest 0.5.4 version and try it again?

**Comment by veronicanoyaro** [comment] 2019-12-04 15:05
Sure!
Thank you very much!

**Comment by EugeneRumynskiy** [comment] 2020-01-13 10:45
@veronicanoyaro How it's going? I'am closing the issue. If you have any questions or unresolved problems please let us know here. If any it's possible to reopen this issue or create a new one.

**Closed by EugeneRumynskiy** 2020-01-13 10:45 UTC
Labels: type:Bug
